# core/single_step.py
from pathlib import Path
from core.agent import Agent


class SingleStep(Agent):
    def process_file(self, split: str, path: Path) -> dict:
        ws = self.step_work_situation(path)  # single agent 1회
        hz = self.step_hazard(path, ws)  # single agent 1회
        cp = self.step_compliance(path, ws, hz)  # ...
        wd = self.step_wearing(path, ws, hz, cp)
        iw = self.step_improper_wearing(path, ws, hz, cp, wd)
        return self.pack_result(path, split, ws, hz, cp, wd, iw)

    # 이 step_* 들은 "단일 에이전트" 1회 호출만 수행하도록 구현
    def step_work_situation(self, path: Path) -> dict: ...
    def step_hazard(self, path: Path, ws: dict) -> dict: ...
    def step_compliance(self, path: Path, ws: dict, hz: dict) -> dict: ...
    def step_wearing(self, path: Path, ws: dict, hz: dict, cp: dict) -> dict: ...
    def step_improper_wearing(
        self, path: Path, ws: dict, hz: dict, cp: dict, wd: dict
    ) -> dict: ...
    def pack_result(self, path: Path, split: str, *steps) -> dict: ...
